import './account';
import './calendar';
import './chat';
import './customers';
import './invoices';
import './kanban';
import './mail';
import './notifications';
import './orders';
import './products';
import './project';
import './reports';
import './search';
import './userroles';
import './roles';
import './cmsusers';
import './companys';
import './module';
import './systemadministrators';
import './social';
import './soscontacts';
import './companies';
import './beneficios';
import './faqs';
import './noticias';
import './language';

// 2020.11.25
import './regal';
import './operation';
import './affiliate';
import './marketing';
import './withdrawal';
import './balance';
import './license';
// 2020.11.25
